baseurl = "/"
canonifyURLs = true
disableHugoGeneratorInject = true
languageCode = "en-us"
paginate = 5
theme = "hello-friend"
timeZone = "America/New_York"

[frontmatter]
  date = ["date", ":filename", "publishDate", "lastmod", ":git"]
  lastmod = ["lastmod", ":git"]
  publishDate = [":default", ":filename"]

[imaging]
  hint = "picture"
  quality = 80
  resampleFilter = "Lanczos"

[params]
  contentTypeName = "posts"
  # defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = true
  # toc = true

[languages]
  [languages.en]
    title = "Hello Friend"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "minute read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    lastModDisplay = "Updated"

    [languages.en.params.logo]
      logoText = "hello friend"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
