name: Deploy Hugo site v2.0

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

env:
  CACHE_ENABLE: true

defaults:
  run:
    shell: bash

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.101.0
    steps:
      - name: Setup cache
        if: env.CACHE_ENABLE == 'true' && github.ref == 'refs/heads/main'
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ github.workflow }}-${{ env.HUGO_VERSION }}

      - name: Link cache
        if: env.CACHE_ENABLE == 'true' && github.ref == 'refs/heads/main'
        run: |
          [[ -d ~/.cache/resources ]] \
          || mkdir ~/.cache/resources \
          && ln --symbolic ~/.cache/resources ./resources

      - name: Install Hugo CLI
        run: |
          [[ -f ~/.cache/hugo.deb ]] \
          || wget -O ~/.cache/hugo.deb https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_$HUGO_VERSION_Linux-64bit.deb \
          && sudo dpkg -i ~/.cache/hugo.deb

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1
        with:
          enablement: false

      - name: Build site
        run: |
          hugo \
            --baseURL ${{ steps.pages.outputs.base_url }} \
            --cacheDir ~/.cache/hugo_cache/ \
            --enableGitInfo \
            --gc \
            --minify \
          || { \
            rm -rf ~/.cache/*; \
            mkdir ~/.cache/resources; \
            exit 1; \
          }

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
    timeout-minutes: 10

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v1
    timeout-minutes: 10
