name: Deploy Hugo site v2.0

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CACHE_ENABLE: true
      HUGO_VERSION: 0.102.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup cache
        if: env.CACHE_ENABLE == 'true' && github.ref == 'refs/heads/main'
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.temp }}/hugo.deb
            /tmp/hugo_cache
            ./resources
          key: ${{ github.workflow }}-${{ env.HUGO_VERSION }}

      - name: Install Hugo CLI
        run: >
          [[ -f ${{ runner.temp }}/hugo.deb ]]
          || wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
        with:
          enablement: false

      - name: Build site
        run: >
          hugo
          --baseURL "${{ steps.pages.outputs.base_url }}/"
          --enableGitInfo
          --gc
          --minify

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
    timeout-minutes: 10

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v1
    timeout-minutes: 10
